name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# ВАЖНО: Даем права на запись в ветку gh-pages
permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright tests with pytest
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2
        continue-on-error: true # Тесты не заблокируют генерацию отчета, если упадут

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Generates Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Move history to report root
        if: always()
        run: |
          cp -r allure-history/* allure-report/
          cp -r gh-pages-dir/history allure-results/ || true

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report # Публикуем allure-report, там БУДЕТ index.html